import Head from 'next/head'
import { Inter } from 'next/font/google'
import HeroSection from '@/Components/Home/HeroSection'
import Navbar from '@/Components/Home/Navbar'
import Overview from '@/Components/Home/Overview'
import Icons from '@/Components/Home/Icons'
import Features from '@/Components/Home/Features'
import Amenities from '@/Components/Home/Amenities'
import FloorPlan from '@/Components/Home/Floor'
import MasterPlan from '@/Components/Home/MasterPlan'
import Location from '@/Components/Home/Location'
import Gallery from '@/Components/Home/Gallery'
import BankSection from '@/Components/Home/Bank'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Navbar />
        <HeroSection />
        <Overview />
        <Icons />
        <Features />
        <Amenities />
        <FloorPlan />
        <MasterPlan />
        <Location />
        <Gallery />
        <BankSection />
      </div>
    </>
  )
}
